---
- name: Add alert policy
  hosts: all
  gather_facts: True
  connection: local
  tasks:
    - name: Create alert policy > 80
      clc_alert_policy:
        alias: wfad
        name: Test policy disk > 80
        alert_recipients:
            - shan.sundaram@centurylink.com
            - shan.sundaram@outlook.com
        metric: 'disk'
        duration: '00:05:00'
        threshold: 80
        state: present
      register: clc
    - pause: seconds=15
    - name: debug
      debug: var=clc
